// Seed list — expanded over time via community tracker lists (EasyList, Disconnect, etc.)
export const KNOWN_TRACKER_DOMAINS = {
  'google-analytics.com': 'analytics',
  'analytics.google.com': 'analytics',
  'googletagmanager.com': 'analytics',
  'doubleclick.net': 'advertising',
  'googlesyndication.com': 'advertising',
  'facebook.com': 'social',
  'connect.facebook.net': 'social',
  'graph.facebook.com': 'social',
  'pixel.facebook.com': 'advertising',
  'hotjar.com': 'analytics',
  'static.hotjar.com': 'analytics',
  'segment.com': 'analytics',
  'cdn.segment.com': 'analytics',
  'api.segment.io': 'analytics',
  'mixpanel.com': 'analytics',
  'amplitude.com': 'analytics',
  'cdn.amplitude.com': 'analytics',
  'fullstory.com': 'fingerprinting',
  'rs6.net': 'crm',
  'criteo.com': 'advertising',
  'criteo.net': 'advertising',
  'adnxs.com': 'advertising',
  'adsrvr.org': 'advertising',
  'rubiconproject.com': 'advertising',
  'scorecardresearch.com': 'analytics',
  'quantserve.com': 'analytics',
  'chartbeat.com': 'analytics',
  'parsely.com': 'analytics',
  'twitter.com': 'social',
  'ads-twitter.com': 'advertising',
  'linkedin.com': 'social',
  'snap.licdn.com': 'social',
  'tiktok.com': 'social',
  'analytics.tiktok.com': 'analytics',
};
